use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::Result;
use serde::Serialize;
use serde_json::Value;

use crate::model::{BodyTemplate, Recipe};

use super::agent_common::{
    PRODUCT_LABEL, TAGLINE, body_template_value, export_slots, headers_map, query_map, recipe_slug,
};

#[derive(Serialize)]
struct McpRecipeTemplate {
    name: String,
    description: String,
    method: String,
    url_template: String,
    headers: BTreeMap<String, String>,
    query: BTreeMap<String, String>,
    body_kind: String,
    body_template: Value,
}

pub fn write_mcp_server_package(recipe: &Recipe, out_dir: &Path) -> Result<()> {
    let server_dir = out_dir.join("mcp-server");
    let src_dir = server_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(server_dir.join("package.json"), package_json(recipe)?)?;
    fs::write(server_dir.join("tsconfig.json"), tsconfig_json())?;
    fs::write(src_dir.join("server.ts"), server_ts(recipe)?)?;
    fs::write(server_dir.join("README.md"), readme_md(recipe))?;
    Ok(())
}

fn package_json(recipe: &Recipe) -> Result<String> {
    let package = serde_json::json!({
        "name": format!("{}-mcp-server", recipe_slug(&recipe.name)),
        "version": "0.1.0",
        "private": true,
        "type": "module",
        "scripts": {
            "build": "tsc",
            "start": "node dist/server.js"
        },
        "dependencies": {
            "@modelcontextprotocol/sdk": "^1.0.0",
            "zod": "^3.23.8"
        },
        "devDependencies": {
            "@types/node": "^20.0.0",
            "typescript": "^5.6.0"
        }
    });
    serde_json::to_string_pretty(&package).map_err(anyhow::Error::from)
}

fn tsconfig_json() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
"#
    .to_string()
}

fn server_ts(recipe: &Recipe) -> Result<String> {
    let recipe_template = McpRecipeTemplate {
        name: recipe_slug(&recipe.name),
        description: TAGLINE.to_string(),
        method: recipe.method.to_ascii_uppercase(),
        url_template: recipe.url_template.clone(),
        headers: headers_map(recipe),
        query: query_map(recipe),
        body_kind: body_kind(&recipe.body_template).to_string(),
        body_template: body_template_value(&recipe.body_template),
    };
    let recipe_json = serde_json::to_string_pretty(&recipe_template)?;
    let input_shape = input_shape_ts(recipe);
    let tool_name = serde_json::to_string(&recipe_slug(&recipe.name))?;
    Ok(SERVER_TS_TEMPLATE
        .replace("__RECIPE_JSON__", &recipe_json)
        .replace("__INPUT_SHAPE__", &input_shape)
        .replace("__TOOL_NAME__", &tool_name)
        .replace("__TOOL_DESCRIPTION__", &serde_json::to_string(TAGLINE)?))
}

fn input_shape_ts(recipe: &Recipe) -> String {
    let slots = export_slots(&recipe.slots);
    if slots.is_empty() {
        return "{}".to_string();
    }
    let fields = slots
        .into_iter()
        .map(|slot| {
            let key = serde_json::to_string(&slot.name).expect("slot names serialize");
            let base = format!("z.string().describe({})", json_string(&slot.location));
            if slot.required {
                format!("  {key}: {base}")
            } else {
                format!("  {key}: {base}.optional()")
            }
        })
        .collect::<Vec<_>>()
        .join(",\n");
    format!("{{\n{fields}\n}}")
}

fn readme_md(recipe: &Recipe) -> String {
    format!(
        "# {} MCP Server\n\nGenerated by {PRODUCT_LABEL}.\n\n{TAGLINE}\n\nThis is a template TypeScript MCP server for the verified recipe `{}`.\n\n## Files\n\n- `package.json`\n- `tsconfig.json`\n- `src/server.ts`\n\n## Notes\n\n- Secrets are read from environment variables only.\n- Do not commit raw secrets.\n- This package is generated as a template; Rust tests do not run npm install, npm build, or TypeScript compilation.\n",
        recipe.name, recipe.name
    )
}

fn body_kind(body: &BodyTemplate) -> &'static str {
    match body {
        BodyTemplate::None => "none",
        BodyTemplate::Json { .. } => "json",
        BodyTemplate::Text { .. } => "text",
        BodyTemplate::Form { .. } => "form",
        BodyTemplate::Multipart { .. } => "multipart",
    }
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serializes")
}

const SERVER_TS_TEMPLATE: &str = r#"import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const RECIPE = __RECIPE_JSON__;
const TOOL_NAME = __TOOL_NAME__;
const TOOL_DESCRIPTION = __TOOL_DESCRIPTION__;

const server = new McpServer({
  name: `${TOOL_NAME}-firstcall`,
  version: "0.1.0",
});

const inputShape = __INPUT_SHAPE__;

server.tool(TOOL_NAME, TOOL_DESCRIPTION, inputShape, async (args) => {
  const url = new URL(fillTemplate(RECIPE.url_template, args));
  for (const [key, value] of Object.entries(RECIPE.query)) {
    url.searchParams.append(key, fillTemplate(String(value), args));
  }

  const headers = {};
  for (const [key, value] of Object.entries(RECIPE.headers)) {
    headers[key] = fillTemplate(String(value), args);
  }

  const init = {
    method: RECIPE.method,
    headers,
  };

  if (RECIPE.body_kind !== "none") {
    const renderedBody = renderTemplateValue(RECIPE.body_template, args);
    if (RECIPE.body_kind === "text") {
      init.body = String(renderedBody);
    } else if (RECIPE.body_kind === "form") {
      init.body = new URLSearchParams(renderedBody).toString();
      headers["content-type"] = headers["content-type"] ?? "application/x-www-form-urlencoded";
    } else {
      init.body = JSON.stringify(renderedBody);
      headers["content-type"] = headers["content-type"] ?? "application/json";
    }
  }

  const response = await fetch(url, init);
  const bodyText = await response.text();
  return {
    content: [
      {
        type: "text",
        text: JSON.stringify({
          status: response.status,
          ok: response.ok,
          body_preview: bodyText.slice(0, 4000),
        }),
      },
    ],
  };
});

function renderTemplateValue(value, args) {
  if (typeof value === "string") {
    return fillTemplate(value, args);
  }
  if (Array.isArray(value)) {
    return value.map((item) => renderTemplateValue(item, args));
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, renderTemplateValue(item, args)]),
    );
  }
  return value;
}

function fillTemplate(value, args) {
  return value.replace(/\$\{([^}]+)\}/g, (_match, name) => {
    if (Object.prototype.hasOwnProperty.call(args, name)) {
      return String(args[name]);
    }
    const fromEnv = process.env[name];
    if (fromEnv) {
      return fromEnv;
    }
    throw new Error(`Missing required value: ${name}`);
  });
}

const transport = new StdioServerTransport();
await server.connect(transport);
"#;
